### ISSUE TITLE
--smtp-port

### ISSUE THREAD

**Issue by timmytr1ll** [tobraha/dattoCheck#10]
Hi, I really appreciate your work. I'm having a heck of a time getting the syntax correct for the --smtp-port switch.

How do i need to define this?

![image](https://user-images.githubusercontent.com/9030977/111684814-2efcf880-87f5-11eb-8668-10893b6bfcea.png)

Thanks!

**Comment by tobraha** [comment]
Hey @timmytr1ll thanks for sending this in.  Turns out I had always just relied on the default port of 25 and the argument parser was handling all input completely wrong.  Also I didn't have port 465 as an option in there.

I just updated the code so you can update it with a ```git pull``` (or just download the code again).

Let me know if that resolves it for you!

**Comment by timmytr1ll** [comment]
Awesome, I just pulled it down and its working great now thank you. How difficult would it be to add 2525? 

Also this is obviously a stretch and I appreciate you even reading this. Do you know of any logic I could add that would show the "unprotected volumes" in the dashboard?

Thanks for getting back to me!

**Comment by tobraha** [comment]
Wouldn't be difficult at all, and now that you mention it I probably shouldn't even restrict the port number input.  If you simply remove line 41 from main.py, you should be able to choose any port number you'd like:

![image](https://user-images.githubusercontent.com/37032081/111691502-00cae900-87f4-11eb-88ab-6a084030ed20.png)

As for the unprotected volumes - yes, this is certainly possible! That data point is available in the API. There would just need to be some added logic in datto/datto.py to add this check. I'll create a new issue for "feature requests" and get this in there.

**Comment by timmytr1ll** [comment]
you are the man. Thank you so much!
