### ISSUE TITLE
Add "Unprotected Volumes" 

### ISSUE THREAD

**Issue by tobraha** [tobraha/dattoCheck#12]
Add a check for unprotected volumes and add to the report.

**Comment by tobraha** [comment]
Refer #10 

![image](https://user-images.githubusercontent.com/37032081/121942145-65231900-cd0d-11eb-95ca-a6d9cff6ae24.png)

Could add a joined 'unprotected_volumes' list to the report with its own column. Would this be too lengthy? Maybe add a command line option to show these?

**Comment by tobraha** [comment]
Hey @timmytr1ll I'm trying to get around to this finally. Are you still using this tool by chance?

If so, how do you think this should be implemented?  Should the report always show the unprotected volumes?  My first thought is that it might make the report too lengthy; I'm considering adding this option as a command-line flag to show the unprotected volumes in the report.  Thanks!

**Comment by timmytr1ll** [comment]
hey @tobraha yes I am. I really like the command line flag option to keep the reports a little cleaner when needed. But beggers can't be choosers. I just appreciate you still supporting the project!

**Comment by tobraha** [comment]
Ok thanks for the input!  I'll try to get this out in the next day or two; I'll @ you when it's done.

The way I'll likely implement this in production would be to have two separate lines for this in crontab: 

* One line that runs the \*extended\* report with the unprotected volumes included on Mondays.
* One to run the normal report (_without_ the unprotected volumes) on Tuesday thru Friday

**Comment by timmytr1ll** [comment]
you are the man. I can't thank you enough. Have a good week

**Comment by timmytr1ll** [comment]
seriously, thank you so much for doing this. killing it my friend lets party

**Comment by tobraha** [comment]
![image](https://media1.giphy.com/media/zhYk9kB2h0yaLfykyW/giphy.gif?cid=ecf05e4761u4vkkil2kwjfbf7ztocbtpbrcw38lnwpa0dyxs&rid=giphy.gif&ct=g)
